FROM bellsoft/bellsoft/liberica-openjdk-alpine:17.0.7
COPY . ./src
RUN mkdir ./out
RUN javac -sourcepath ./src -d ./out src/java/ru/geekbrains/jc/hw/first/MainApp
CMD java -classpath ./out ru.geekbrains.jc.hw.first.MainApp